# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def even_fibonacci():
	new_term = 0
	n1, n2 = 1, 2  #fibonnacci starting two terms
	while n1 <= 4000000:	
		if n1 % 2 == 0:
			new_term += n1
		n1, n2 = n2, n1+n2  #updating the fibonacci numbers			
	return str(new_term)	

if __name__ == '__main__':
	print(even_fibonacci())